os:
  - linux
  - osx

language: bash

install:
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

script:
  - ./tests/checkstyle/checkstyle.sh
  - ./tests/unit-tests/unit-tests.sh
  - ./tests/integ-tests/integ-tests.sh
